### ISSUE TITLE
Post links to your personal GitHub repositories

### ISSUE THREAD

**Issue by rickecon** [UC-MACSS/persp-research_Spr18#1]
Class members need to copy the URL to their personal repositories for this course in a comment on this issue. The URL's should have the form described in the README for this repository.

`github.com/YourGithubHandle/MACS30200proj/`

**Comment by jfan3** [comment]
https://github.com/jfan3/MACS30200proj

**Comment by jgdenby** [comment]
https://github.com/jgdenby/MACS30200proj

**Comment by bethbailey** [comment]
https://github.com/bethbailey/MACS30200proj

**Comment by uc-xic** [comment]
https://github.com/uc-xic/MACS30200proj

**Comment by uofcyx** [comment]
https://github.com/uofcyx/MACS30200proj

**Comment by bensoltoff** [comment]
Got Github usernames from submissions in the first two terms. No longer necessary

**Comment by uofcyx** [comment]
Hi Dr. Soltoff, I wasn't here in the first two terms so I just wanted to double check that you have my repo URL on file. Thx!

**Comment by bensoltoff** [comment]
Yes I got it from last year

**Comment by yilundai** [comment]
https://github.com/yilundai/MACS30200Proj

**Comment by Fangfangwan** [comment]
https://github.com/Fangfangwan/MACS30200proj
