### ISSUE TITLE
Isses rendering surface plot in python for question #2

### ISSUE THREAD

**Issue by TCurran4589** [UC-MACSS/persp-research_Spr18#24]
I am trying to create a surface plot for the interaction terms for question 2 using python and plotly and I can get the axis to show up but the data itself will not render. I also tried this in R and ran into the same issue. 

Suggestions?

![screen shot 2018-04-29 at 2 06 31 pm](https://user-images.githubusercontent.com/4342457/39410027-91f69faa-4bb6-11e8-8063-7d7787d2db35.png)

**Comment by bensoltoff** [comment]
Are you adding a surface or mesh layer? There is a difference between the two

**Comment by TCurran4589** [comment]
its a meshlayer I believe

My Code:

`plot = go.Mesh3d(
    
    x = x,
    y = y,
    z = z,
    opacity = 0,
    color = "rgb(39, 100, 0)"
)

layout = go.Layout(
                    scene = dict(
                        xaxis = dict(title='Age'),
                        yaxis = dict(title='Education'),
                        zaxis = dict(title='Biden')),
                    width=700)


fig = go.Figure(data = [plot], layout = layout)

py.iplot(fig)`

and the example I am using from plotly API:  https://plot.ly/python/3d-axes/

**Comment by TCurran4589** [comment]
Fixed,

Had to convert x y and z to np arrays
